apiVersion: v1
data:
  configManagementPlugins: |-
    - name: argocd-lovely-plugin
      init:
        command: ["argocd-lovely-plugin"]
        args: ["init"]
      generate:
        command: ["argocd-lovely-plugin"]
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
