apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-nginx-world
  namespace: argocd
spec:
  destination:
    namespace: multiple-helm
    server: 'https://kubernetes.default.svc'
  source:
    path: examples/multiple-helm-charts/charts
    repoURL: 'https://github.com/crumbhole/argocd-lovely-plugin.git'
    targetRevision: HEAD
    plugin:
      name: argocd-lovely-plugin
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=background
      - CreateNamespace=true