name: Build and test

on:
  pull_request:
    branches: [ main ]

jobs:
  gogitops:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: GoGitOps Step
      id: gogitops
      uses: beaujr/gogitops-action@v0.2
      with:
        github-actions-token: ${{secrets.GITHUB_TOKEN}}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Get
      run: go get -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  k3d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: AbsaOSS/k3d-action@v2
        name: "Create single k3d Cluster with imported Registry"
        with:
          cluster-name: test-cluster-1
          args: >-
            --agents 3
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
      - name: "Docker repo demo"
        run: |
          docker build . -t myproj/demo:v1.0.0
          k3d image import myproj/demo:v1.0.0 -c test-cluster-1 --verbose
          kubectl apply -f .github/workflows/assets/pod.yaml
      - name: Cluster info
        run: |
          kubectl cluster-info --context k3d-test-cluster-1
      - name: Nodes
        run: |
          docker ps -a
          kubectl config use-context k3d-test-cluster-1
          kubectl get nodes -o wide
      - name: Network
        run: docker network inspect k3d-test-cluster-1
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/amd64, linux/arm64
          tags: ghcr.io/crumbhole/argocd-lovely-plugin:pull
